### ISSUE TITLE
Неработающие ссылки.

### ISSUE THREAD

**Issue by AlwaysWithSmile** [bogdansemkin/mta-miracle#11]
@bogdansemkin , Привет! Последний раз мы общались в 2018 году, но сейчас я решил просмотреть github и увидел этот репозиторий, отсюда и появились вопросы. 

1. MTA Miracle - это ведь уже неработающий проект, который ты закрыл под слоганом ~Уже неактуально~, а сейчас ЭТО находится в пине. Что?

2. Такие ссылки как:
https://vk.com/kapitoshka_b
http://bs-mta.ru/
являются нерабочими. 

3.Переводить уже тоже не видно чего, ибо никнейм изменён, просьба исправить.

**Comment by bogdansemkin** [comment]
Проект закрыт. Репозиторий - архив прошлого.
 ~https://vk.com/kapitoshka_b~  - Старая страница будущего на тот момент руководителя проекта. 
~http://bs-mta.ru/~ - Старый web-page проекта.

С 2018 года я не имею никакого отношения к проекту как по личному, так и по открытому фактору(Переезд с Киева в Москву, с Москвы в Пекин). Надеюсь, я ответил на ваш вопрос и желаю вам хорошего дня. Issue #11 будет удалён ботом в течении месяца, потому, если хотите, можете закинуть его себе в архив.
